FROM python:3.5-slim

# ugly workaround to allow the main script to be called via
# ./codeship/functional_tests.sh
RUN mkdir -p /codeship/codeship
WORKDIR /codeship

RUN mkdir -p /splunk/plugin

COPY ./test/requirements.txt ./
RUN  pip install -r requirements.txt

COPY ./test/ ./
COPY ./codeship/functional_tests.sh ./
